describe('test daf', function() {
  it('login', () => {
    cy.visit('/login')
    cy.contains('欢迎您使用电子申请表')
    cy.get('.imgOTP').should('have.attr', 'src').and('include', 'https://posuat1.mercedes-benz-finance.com.cn/cicd-mobile/e-app//api/digitalform/GetIdentifyImage?key=')
    cy.get('#phone').type('17610282917')
    cy.get('input[name="图片验证码"]').type('1234')
    cy.get('#valid').click()
    cy.get('.mask .modal .modal-content .button').click()
    cy.get('.mask').should('not.be.visible')
    cy.get('input[name="验证码"]').type('123456')
    cy.get('.login-button').click()
    cy.url().should('include', 'ekyc')
    cy.get('.logout')
    // cy.get('iframe').should('have.attr', 'src').and('include', 'https://posuat1.mercedes-benz-finance.com.cn/ekyc/index.html')
    // cy.get('.mint-indicator').should('not.be.visible')
    // cy.contains('#front-upload-form > .upload-container > label', '上传身份证正面')
    // cy.contains('#back-upload-form > .upload-container > label', '上传身份证背面')
  })
})
